apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flp
  labels:
    k8s-app: flp
spec:
  selector:
    matchLabels:
      k8s-app: flp
  template:
    metadata:
      labels:
        k8s-app: flp
    spec:
      serviceAccountName: ebpf-agent-test
      containers:
        - name: flp
          image: quay.io/netobserv/flowlogs-pipeline:main
          ports:
            - containerPort: 9999
              hostPort: 9999
              protocol: UDP
          args:
            - --config=/etc/flp/config.yaml
          volumeMounts:
            - mountPath: /etc/flp
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: flp-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flp-config
data:
  config.yaml: |
    log-level: debug
    pipeline:
      - name: ingest
      - name: interface
        follows: ingest
      - name: enrich
        follows: interface
      - name: loki
        follows: enrich
    parameters:
      - name: ingest
        ingest:
          type: collector
          collector:
            hostName: 0.0.0.0
            port: 9999
      - name: interface
        transform:
          type: generic
          generic:
            policy: preserve_original_keys
            rules:
              - input: TimeReceived
                output: Interface
      - name: enrich
        transform:
          type: network
          network:
            rules:
              - type: add_kubernetes
                kubernetes:
                  input: SrcAddr
                  output: SrcK8S
              - type: add_kubernetes
                kubernetes:
                  input: DstAddr
                  output: DstK8S
      - name: loki
        write:
          type: loki
          loki:
            staticLabels:
              app: netobserv-flowcollector
            labels:
              - "SrcK8S_Namespace"
              - "SrcK8S_OwnerName"
              - "DstK8S_Namespace"
              - "DstK8S_OwnerName"
              - "FlowDirection"
            url: http://loki:3100
            timestampLabel: TimeFlowEndMs
            timestampScale: 1ms 
