name: Pull request checks

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.21','1.22']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}
    - name: Install make
      run: sudo apt -y install make
    - name: Run verification and tests
      run: make lint test cov-exclude-generated
    - name: check clean generate
      run: make docker-generate && git add -A && git diff HEAD --exit-code
    - name: check clean vendors
      run: go mod vendor
    - name: Report coverage
      if: ${{ matrix.go == '1.21' }}
      uses: codecov/codecov-action@v4
      with:
        files: ./cover.out
        flags: unittests
        fail_ci_if_error: false
        verbose: true
